### ISSUE TITLE
Question about Tinits, Nölle & Hartmann (2017)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#105]
Document Key:tinits2017usage
Contributors: @Jonas-N @peeter-t2

Thanks for adding this paper!  I'd just like to check the links you marked with a ">>" relation.  These are reserved for necessary preconditions (as opposed to a more general causal influence).  Is this what you mean?

I also wondered what the interpretation this link:
"increase in overspecification" > "iterated learning"
I guess it doesn't mean that an increase in overspecification leads to more iterated learning, nor that overspecification makes iterated learning possible.  Some restructuring, or adding some quotes would help.

(btw, this is not an admonishment - the discussion here is just meant to refine the expression of your work)

**Comment by Jonas-N** [comment]
Hey, yeah I wasn't sure how to express that the experimental condition determined the referential complexity /relevant feature dimensions (I thought maybe "correlation" is not right here, because it is simply if ... then....). The idea with IL was that the increase at overspecification that happens in each condition for each participants is then amplified over transmission through cog. bias/error.

Btw, I tried to update the graph, do I just "submit" again?

Best,

Jonas


________________________________
Von: Sean Roberts <notifications@github.com>
Gesendet: Mittwoch, 28. März 2018 14:41
An: CHIELDOnline/CHIELD
Cc: Jonas Nölle; Mention
Betreff: [CHIELDOnline/CHIELD] Question about Tinits, Nölle & Hartmann (2017) (#105)


Document Key:tinits2017usage
Contributors: @Jonas-N<https://github.com/Jonas-N> @peeter-t2<https://github.com/peeter-t2>

Thanks for adding this paper! I'd just like to check the links you marked with a ">>" relation. These are reserved for necessary preconditions (as opposed to a more general causal influence). Is this what you mean?

I also wondered what the interpretation this link:
"increase in overspecification" > "iterated learning"
I guess it doesn't mean that an increase in overspecification leads to more iterated learning, nor that overspecification makes iterated learning possible. Some restructuring, or adding some quotes would help.

(btw, this is not an admonishment - the discussion here is just meant to refine the expression of your work)

**Comment by seannyD** [comment]
The graph is meant to express your hypothesis about the phenomenon you're studying, not necessarily your experimental design.  The causal arrows are supposed to suggest causation (not just correlation), but the ">>" relation is supposed to be for necessary preconditions.  e.g. [Cuthbertson (2012)](http://localhost/CHIELD/Site/document.html?key=evolang11_26) suggests that certain levels of theory of mind are a prerequisite for emulation/imitation.

Re: editing: Yes, if you clicked "Edit Data", you should get the same "addData" page, with your details already filled out.  Edit what you want, then click "submit".  It'll create a pull request to edit the current files in the repository.

**Comment by Jonas-N** [comment]
Thanks a lot, and sorry, I was a bit overenthusiastic and jumped right into creating the graph without paying too much attention to the "help" page, which is actually super useful. I'll revise the graph!
