### ISSUE TITLE
Question about Trudgill (2011)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#111]
Document: [https://chield.excd.org/document.html?key=trudgill2011social](https://chield.excd.org/document.html?key=trudgill2011social)
Contributors: @peeter-t2 

Can you explain why you're using the "^" relation?  I was hoping to avoid this as much as possible.  For example, this quote seems to suggest just a straightforward causal link?
>    "There is considerable evidence to show that short-term adult language contact leads to simplification in phonology."

Also, is there a reason to use "community size" rather than "population size"? Currently, more papers use "population size", and I think they mean the same thing?

**Comment by peeter-t2** [comment]
Wasn't sure exactly when to use "^", due to the reasons explained for Kusters too. But considering that language change is short-term, these are all easy causal links. Submitted an edit fixing it.

Also changed to population size, since it is exactly equivalent. There is probably more room for terminological standardization.
