### ISSUE TITLE
Question about Fay, Lister, Ellison & Goldin-Meadow (2014)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#148]
Document: [fay2014creating](https://chield.excd.org/document.html?key=fay2014creating)
Contributors: @hanachronism 

I'm finding it difficult to interpret this.  Quotes from the paper would help, but I also wonder if the direction of causality is the right way around.
e.g.:
iconicity > communicative needs
Does this mean that more iconicity changes what you need to talk about?
Also:
sign alignment >>  communicative needs
Why does this use the ">>" relation (necessary condition)? Being able to align signs is a prerequisite for having communicative needs?

**Comment by hanachronism** [comment]
> Does this mean that more iconicity changes what you need to talk about?

No, I meant that iconicity facilitates communication. We should probably delete that link because I see what is meant by "communicate needs" now.

>  Being able to align signs is a prerequisite for having communicative needs?

Again, this is just me not understanding what was meant by communicative needs, I just meant communication (and yes, aligning signs is a prerequisite for communication)
