### ISSUE TITLE
no reference listed

### ISSUE THREAD

**Issue by SimonGreenhill** [CHIELDOnline/CHIELD#264]
...why does [this](https://chield.excd.org/variable.html?key=3284661260) not list a reference?

**Comment by seannyD** [comment]
Fixed, but haven't tracked down ultimate cause.

There was no reference because nettle2012social.csv had the bibref information in two columns (one with a blank name).  The bibref column is added in the addData page by these lines in `submitToGithub.js`:

```
// Add the bibref to every line
for(var i=0; i < data.length; ++i){
	data[i].bibref = bib_key;
}
```

Perhaps this is adding extra columns? Or the JSONToCSVConvertor function is getting confused by null values somewhere?  There are actually several csv files with empty columns.

Out of time just now.

**Comment by SimonGreenhill** [comment]
I don't know js very well, but that loop could be giving an off-by-one error? (i.e. do arrays start at 0? does postincrement ++i differ from preincrement i++?)

**Comment by SimonGreenhill** [comment]
This looks fixed now.
