### ISSUE TITLE
Question about Richerson & Boyd (2010)

### ISSUE THREAD

**Issue by seannyD** [CHIELDOnline/CHIELD#339]
Document: [richerson2010possibly](https://chield.excd.org/document.html?key=richerson2010possibly)
Contributors: @abuskell 

Nice! Excellent use of quotes.

One question: I think the indicator connections might be the wrong way around. X ~= Y means that X is measured by Y. So shouldn't cooperation be measured by cooperative hunting, rather than the other way around? 

I'm also not sure about these links:
trust: across-group ~= ethnic group diversity
cooperation ~= cultural variability: within-group
(these seem like causal connections?)

cultural complexity: institutions ~= cooperation
(Maybe the other way around, or increase in cooperation makes it more likely for institutions to emerge? Or is this co-evolving?)

You can edit the graph by going to its document page ([here](https://chield.excd.org/document.html?key=richerson2010possibly)) and clicking "Edit Data".

**Comment by abuskell** [comment]
Huzzah! Exciting to be a part of this project!

Thanks. Yes, I had understood X~=Y to mean that X is a measure of Y. So you're right, the indicator connections are all the wrong way round. Apologies! I've gone back and fixed those that remained after the changes below.

About the specific links (with corrected indicator connections):
ethnic group diversity ~= trust: across-group: at least as I read the paper, there's not a specific causal link proposed. Even given some of the suggestive comments, it's further unclear where the lines of causation should point, or whether the authors think the population-level trait (trust: across-group) coevolves with ethnic group diversity (this seems the most plausible suggestion, given the paper). I've not edited this edge; what do you suggest?

cultural variability ~=cooperation. I had put this in because it seemed implied by the other aspects of the paper, but now I'm unsure. Especially given the lack of textual support here, I've decided to turf this.

cooperation ~= cultural complexity: institutions. Yes, I think you're right about the causal claim, especially given the supporting quote. I've changed the indicator to reflect this

**Comment by SimonGreenhill** [comment]
Looks like those changes didn't come through?

**Comment by abuskell** [comment]
Dear both,

Thanks for this. I thought I had tweaked this not long after Sean's prod,
and indeed, it seems that some of these relationships had already been
changed (though not cooperation ~=cooperative hunting). I'll try to revisit
the document and double-check the network in the upcoming days.

All best,
Andrew
